#!/bin/bash
cd precompiled
FILES=*.dll
for f in $FILES
do
  if [ -f /Library/Frameworks/Mono.framework/Libraries/mono/4.5/$f ]
  then
    cp /Library/Frameworks/Mono.framework/Libraries/mono/4.5/$f .
  fi
done
