#!/bin/bash
cd precompiled
FILES=*.dll
DIR=/Library/Frameworks/Mono.framework/Libraries/mono/4.5
unamestr=`uname`
if [[ "$unamestr" == 'Linux' ]]; then
  DIR=/usr/lib/mono/4.5
fi
for f in $FILES
do
  if [ -f $DIR/$f ]
  then
    cp $DIR/$f .
  fi
done
